[general]
import = ['~/.config/i3/conf/alacritty-padding.toml']

[window]
decorations="full"
dynamic_title=true
opacity = 0.9
dynamic_padding = true

[font]
size = 15

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#161012"
foreground = "#c4c3c3"

[colors.cursor]
text = "#161012"
cursor = "#c4c3c3"

[colors.vi_mode_cursor]
text = "#161012"
cursor = "#c4c3c3"

[colors.search.matches]
foreground = "#161012"
background = "#c4c3c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#6f5a5f"
background = "#c4c3c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#161012"
red = "#C77836"
green = "#DB8E43"
yellow = "#35578A"
blue = "#506F9E"
magenta = "#837D84"
cyan = "#7089B1"
white = "#c4c3c3"

[colors.bright]
black = "#6f5a5f"
red = "#C77836"
green = "#DB8E43"
yellow = "#35578A"
blue = "#506F9E"
magenta = "#837D84"
cyan = "#7089B1"
white = "#c4c3c3"

[colors.dim]
black = "#c4c3c3"
red = "#C77836"
green = "#837D84"
yellow = "#35578A"
blue = "#506F9E"
magenta = "#DB8E43"
cyan = "#7089B1"
white = "#6f5a5f"
