[general]
import = ['~/.config/i3/conf/alacritty-padding.toml']

[window]
decorations="full"
dynamic_title=true
opacity = 0.9
dynamic_padding = true

[font]
size = 15

[font.normal]
family='Mononoki Nerd Font'

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Mononoki Nerd Font'
style='italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && zsh"]
[colors.primary]
background = "#2b2837"
foreground = "#cac9cd"

[colors.cursor]
text = "#2b2837"
cursor = "#cac9cd"

[colors.vi_mode_cursor]
text = "#2b2837"
cursor = "#cac9cd"

[colors.search.matches]
foreground = "#2b2837"
background = "#cac9cd"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#706b84"
background = "#cac9cd"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#2b2837"
red = "#77A4C7"
green = "#C293B7"
yellow = "#91A3DB"
blue = "#94B5E5"
magenta = "#AFB7E9"
cyan = "#E9B4DF"
white = "#cac9cd"

[colors.bright]
black = "#706b84"
red = "#77A4C7"
green = "#C293B7"
yellow = "#91A3DB"
blue = "#94B5E5"
magenta = "#AFB7E9"
cyan = "#E9B4DF"
white = "#cac9cd"

[colors.dim]
black = "#cac9cd"
red = "#77A4C7"
green = "#AFB7E9"
yellow = "#91A3DB"
blue = "#94B5E5"
magenta = "#C293B7"
cyan = "#E9B4DF"
white = "#706b84"
