[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 15

[font.normal]
family='Mononoki Nerd Font'
style="bold"

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Victor Mono'
style='Bold Italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && export ZSH_ISOLATE=1 && zsh"]
[colors.primary]
background = "#16201e"
foreground = "#c4c7c6"

[colors.cursor]
text = "#16201e"
cursor = "#c4c7c6"

[colors.vi_mode_cursor]
text = "#16201e"
cursor = "#c4c7c6"

[colors.search.matches]
foreground = "#16201e"
background = "#c4c7c6"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5f756f"
background = "#c4c7c6"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#16201e"
red = "#95A8A5"
green = "#BDBCB2"
yellow = "#DDC9B8"
blue = "#95B4CE"
magenta = "#ADD2DB"
cyan = "#DBD7D1"
white = "#c4c7c6"

[colors.bright]
black = "#5f756f"
red = "#95A8A5"
green = "#BDBCB2"
yellow = "#DDC9B8"
blue = "#95B4CE"
magenta = "#ADD2DB"
cyan = "#DBD7D1"
white = "#c4c7c6"

[colors.dim]
black = "#c4c7c6"
red = "#95A8A5"
green = "#ADD2DB"
yellow = "#DDC9B8"
blue = "#95B4CE"
magenta = "#BDBCB2"
cyan = "#DBD7D1"
white = "#5f756f"
