[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 15

[font.normal]
family='Mononoki Nerd Font'
style="bold"

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Victor Mono'
style='Bold Italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && export ZSH_ISOLATE=1 && zsh"]
[colors.primary]
background = "#201812"
foreground = "#c7c5c3"

[colors.cursor]
text = "#201812"
cursor = "#c7c5c3"

[colors.vi_mode_cursor]
text = "#201812"
cursor = "#c7c5c3"

[colors.search.matches]
foreground = "#201812"
background = "#c7c5c3"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#73665e"
background = "#c7c5c3"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#201812"
red = "#D8A76C"
green = "#EDB677"
yellow = "#DEC26F"
blue = "#FCC67C"
magenta = "#44B281"
cyan = "#E3B482"
white = "#c7c5c3"

[colors.bright]
black = "#73665e"
red = "#D8A76C"
green = "#EDB677"
yellow = "#DEC26F"
blue = "#FCC67C"
magenta = "#44B281"
cyan = "#E3B482"
white = "#c7c5c3"

[colors.dim]
black = "#c7c5c3"
red = "#D8A76C"
green = "#44B281"
yellow = "#DEC26F"
blue = "#FCC67C"
magenta = "#EDB677"
cyan = "#E3B482"
white = "#73665e"
