[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 15

[font.normal]
family='Mononoki Nerd Font'
style="bold"

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Victor Mono'
style='Bold Italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && export ZSH_ISOLATE=1 && zsh"]
[colors.primary]
background = "#121114"
foreground = "#c3c3c4"

[colors.cursor]
text = "#121114"
cursor = "#c3c3c4"

[colors.vi_mode_cursor]
text = "#121114"
cursor = "#c3c3c4"

[colors.search.matches]
foreground = "#121114"
background = "#c3c3c4"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a5a6f"
background = "#c3c3c4"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#121114"
red = "#B8927A"
green = "#667390"
yellow = "#4259A4"
blue = "#7587A4"
magenta = "#719DCF"
cyan = "#9598A7"
white = "#c3c3c4"

[colors.bright]
black = "#5a5a6f"
red = "#B8927A"
green = "#667390"
yellow = "#4259A4"
blue = "#7587A4"
magenta = "#719DCF"
cyan = "#9598A7"
white = "#c3c3c4"

[colors.dim]
black = "#c3c3c4"
red = "#B8927A"
green = "#719DCF"
yellow = "#4259A4"
blue = "#7587A4"
magenta = "#667390"
cyan = "#9598A7"
white = "#5a5a6f"
