[general]
import = ['~/.config/i3/conf/alacritty-extra.toml']

[window]
decorations="full"
dynamic_title=true

[font]
size = 15

[font.normal]
family='Mononoki Nerd Font'
style="bold"

[font.bold]
family='MonaspiceRN NFM'
style="bold"

[font.italic]
family='Victor Mono'
style='Bold Italic'

[terminal]

[terminal.shell]
program = "/bin/sh"
args = ["-c", "export ZDOTDIR=/home/_3hy/.config/i3/conf/ && export ZSH_ISOLATE=1 && zsh"]
[colors.primary]
background = "#0b1419"
foreground = "#c2c4c5"

[colors.cursor]
text = "#0b1419"
cursor = "#c2c4c5"

[colors.vi_mode_cursor]
text = "#0b1419"
cursor = "#c2c4c5"

[colors.search.matches]
foreground = "#0b1419"
background = "#c2c4c5"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#5a676e"
background = "#c2c4c5"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0b1419"
red = "#0B4F90"
green = "#155AA2"
yellow = "#2F64A9"
blue = "#5974B6"
magenta = "#747FC0"
cyan = "#7B81C0"
white = "#c2c4c5"

[colors.bright]
black = "#5a676e"
red = "#0B4F90"
green = "#155AA2"
yellow = "#2F64A9"
blue = "#5974B6"
magenta = "#747FC0"
cyan = "#7B81C0"
white = "#c2c4c5"

[colors.dim]
black = "#c2c4c5"
red = "#0B4F90"
green = "#747FC0"
yellow = "#2F64A9"
blue = "#5974B6"
magenta = "#155AA2"
cyan = "#7B81C0"
white = "#5a676e"
